services:
  # Serviço de produção
  tarefas-app:
    container_name: tarefas-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  # Serviço de desenvolvimento
  tarefas-dev:
    container_name: tarefas-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: sleep infinity
    networks:
      - app-network
    profiles:
      - dev

networks:
  app-network:
    driver: bridge
