import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "../components/Header";

import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Tarefa+ | Organize suas tarefas de forma fácil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="antialiased">
        <div className="container">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
