
import Image from "next/image";

export const metadata = {
  title: "Tarefa+ | Organize suas tarefas de forma fácil",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <main className="main">
        <div className="logoContent">
          <Image
            className="hero"
            src="/assets/hero.png"
            alt="Hero Image"
            priority
            width={500}
            height={400}
            unoptimized
          />
        </div>
      </main>
      <h1 className="title">Sistema feito para você organizar
        <br /> seus estudos e tarefas
      </h1>

      <div className="infoContent">
        <section className="box">
          <span>+12 posts</span>
        </section>
        <section className="box">
          <span>+90 comentários</span>
        </section>
      </div>
    </>
  );
}