import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Tarefa+ | Organize suas tarefas de forma fácil",
  description: "Generated by create next app",
};

async function getServerSideProps() {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/");
  }
  return { props: { session } };
}

export default async function Dashboard () {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/");
  }
  return (
    <div className="main">
      <h1>Paginal painel</h1>
    </div>
  )
}
