import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import TextArea from "../../components/textarea";
import styles from "./styles.module.css"

export const metadata = {
  title: "Tarefa+ | Painel de tarefas",
  description: "Generated by create next app",
};

async function getServerSideProps() {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/");
  }
  return { props: { session } };
}

export default async function Dashboard () {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/");
  }
  return (
    <div className={styles.container}>
      <div className={styles.main}>
        <section className={styles.content}>
          <div className={styles.contentForm}>
            <h1 className={styles.title}>Qual sua Tarefa</h1>

            <form action="">
              <TextArea placeholder="Qual sua tarefa?" />
              <div className={styles.checkboaArea}>
                <input type="checkbox" className={styles.checkbox} id="checbox_area" />
                <label htmlFor="checkbox_area" className={styles.label_form}>Deixar a tarefa publica?</label>

              </div>
              <button className={styles.button} type="submit">Registrar</button>

            </form>
          </div>
        </section>

        <section className={styles.taskContainer}>
          <h2 className={styles.title}>Minhas tarefas</h2>
          
        </section>
      </div>
    </div>
  )
}
